### ISSUE TITLE
Command-line documentation errors

### ISSUE THREAD

**Issue by notsafeforbread** [intiface/intiface-engine#4]
Of those I noticed during a quick test:

The command-line documentation uses underscores, but the executable's command line options all use hyphens instead.
The readme lists the websocket port command as `websocket_peport [port]` however it should be `websocket-port`.
At the bottom of the "running" section, it uses `--wsinsecureport` when it should be `--websocket-port`. and `--use_bluetooth_le` when it should be `--use-bluetooth-le`

The documentation from running `./intiface-engine --help` appears to be correct.

**Comment by qdot** [comment]
Thanks, totally missed that when I overhauled the arguments for v1. Fixed in README on dev now. Probably on master within the week.
