### ISSUE TITLE
Issues with building for IOS

### ISSUE THREAD

**Issue by biclighter81** [intiface/intiface-engine#7]
Hey,
I'm trying to build the intiface-engine for ios to use it with dart ffi. But no matter which rust target I'm using out of:

`aarch64-apple-ios (installed),
aarch64-apple-ios-sim (installed),
x86_64-apple-ios (installed)`

I'm always getting the error:

`
linking with cc failed: exit status: 1
[...]
note: ld: framework not found AppKit
          clang: error: linker command failed with exit code 1
`

I have no experience with xcode or building for ios / macos devices but it seems like AppKit is a MacOs only feature. Why is the intiface-engine and also the buttplug crate itself using it when I'm building for ios? Is it even possible to build the intiface flutter repository for ios and android? Because if i run flutter build for ios I'm getting the same error.

Thank you.
Moritz

**Comment by qdot** [comment]
Couldn't tell you. Neither Intiface nor Buttplug have any platform specific code in them that would cause this. Only our bluetooth bindings do, and that's corebluetooth shared across iOS/macOS. 

I've built for iOS just fine with this library as a dependency, so it may be something in your specific build chain. If you're trying to build a cross language binding that use hardware APIs for iOS and you don't know XCode and the Apple toolchains *extremely* well, you are in for untold amounts of suffering.

**Comment by biclighter81** [comment]
First of all thank you four your quick reply. 
Sorry for bothering you again but is it really related to xcode build configurations when I'm just trying to build the intiface-engine library? My issue is fairly simple to reproduce: I'm cloning the intiface-engine library on an apple M1 Pro and executing `cargo build --target aarch64-apple-darwin` which works perfectly. The generated intiface-engine file in `target/aarch64-apple-darwin` is an executable cli as expected. Running `cargo build --release --target aarch64-apple-ios` results in the error I provided yesterday. Do I already need a xcode project to build the library? How are you building for ios? I would be more than happy if you could provide me your build commands.
